In [5]:
import numpy as np

In [1]:
%timeit L = [n ** 2 for n in range(1000)]

325 µs ± 5.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [2]:
%%timeit
sum(range(100))

1.28 µs ± 30 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [3]:
%config IPCompleter.greedy=True

# Arrays from scratch

In [6]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [7]:
print(x1);print(x2);print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [8]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [9]:
x2[:2,:3]

array([[3, 5, 2],
       [7, 6, 8]])

In [10]:
x2[:3,::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

## 2-D Array逆序

In [11]:
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

## Array slicing - Subarrays as no-copy views---Amazing!!

In [12]:
x2_sub=x2[:2,:2]

In [13]:
x2_sub

array([[3, 5],
       [7, 6]])

In [14]:
x2_sub[0,0]=99

In [15]:
x2

array([[99,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [18]:
x2_sub_=x2[:2,:2].copy()

In [19]:
x2_sub_[0,0]=77
print(x2_sub_);print(x2)

[[77  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [24]:
x=np.array([1,2,3])

In [25]:
x.reshape(-1,1) #也可以变成列column

array([[1],
       [2],
       [3]])

In [23]:
x.reshape(x.shape[0],1)

array([[1],
       [2],
       [3]])

## Array Concatenation

In [26]:
x = np.array([1, 2, 3]) 
y = np.array([3, 2, 1]) 
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [27]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [28]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

In [31]:
np.concatenate([grid, grid]) 



array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [32]:
np.concatenate([grid, grid], axis= 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [36]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

x = np.array([1, 2, 3])

y = np.array([[99], [99]])
print("x=: ",x);print("y=: ",y)
np.vstack([x, grid]) 


x=:  [1 2 3]
y=:  [[99]
 [99]]


array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [35]:
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

## Splitting Arrays

In [37]:
x = [1, 2, 3, 99, 99, 3, 2, 1] 
x1, x2, x3 = np.split(x, [3, 5]) 
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [38]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
upper, lower = np.vsplit(grid, [2]) 
print(upper)

print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


## NumPy Arrays: Universal Functions

In [43]:
x1=1.0/np.arange(1,5)
x2=np.arange(5) / np.arange(2, 7)
x = np.arange(9).reshape((3, 3)) 
x3=2 ** x

In [44]:
print(x1);print(x2);print(x);print(x3)

[1.         0.5        0.33333333 0.25      ]
[0.         0.33333333 0.5        0.6        0.66666667]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]


In [45]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division (quotient)
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2) # remainder

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [49]:
x = np.arange(5)

y = np.empty(5) 
print(y)
np.multiply(x, 10, out=y) 
print(y)

[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323]
[ 0. 10. 20. 30. 40.]


In [51]:
x = np.arange(1, 6) 
print(x)
np.add.reduce(x)

[1 2 3 4 5]


15

In [52]:
M = np.random.random((3, 4))

print(M)

[[0.65279032 0.63505887 0.99529957 0.58185033]
 [0.41436859 0.4746975  0.6235101  0.33800761]
 [0.67475232 0.31720174 0.77834548 0.94957105]]


In [53]:
M.sum()

7.435453494015987

In [54]:
M.min(axis=0)

array([0.41436859, 0.31720174, 0.6235101 , 0.33800761])

In [55]:
M.max(axis=1)

array([0.99529957, 0.6235101 , 0.94957105])

# PANDAS & DATASTRUCTURS

In [57]:
import pandas as pd

In [58]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])

In [59]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [62]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
'Florida': 170312, 'Illinois': 149995} 
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [64]:
population_dict = {'California': 38332521, 'Texas': 26448193,
'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135}

population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [65]:
states = pd.DataFrame({'population': population,
'area': area})

In [66]:
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [67]:
data = [{'a': i, 'b': 2 * i} for i in range(3)]

In [68]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

## Index object

Any list of values, even It is an the values can repeat immutable array

In [ ]:
ind = pd.Index([2, 3, 5, 7, 11])

Missing Values are always a NaN in pandas

In [73]:
data=pd.Series([1, np.nan, 2, None, 3])
data

0    1.0
1    NaN
2    2.0
3    NaN
4    3.0
dtype: float64

In [72]:
data.fillna(method='ffill')

0    1.0
1    1.0
2    2.0
3    2.0
4    3.0
dtype: float64

## MultiIndex
Caution!
Not well organized & Not recomended

In [74]:
index = [('California', 2000), ('California', 2010),
('New York', 2000), ('New York', 2010),
('Texas', 2000), ('Texas', 2010)] 
populations = [33871648, 37253956,18976457, 19378102,20851820, 25145561]

In [76]:
pop = pd.Series(populations, index=index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [77]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [78]:
pop = pop.reindex(index) 
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

## Pandas concat

In [79]:
def make_df(cols, ind): 
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind] for c in cols}
    return pd.DataFrame(data, ind)

### full JOIN Concat

In [80]:
df5=make_df('ABC',[1,2])
df6=make_df('BCD',[3,4])
pd.concat([df5,df6])

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [81]:
pd.concat([df5,df6],join='inner')

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

** Pandas offers join Types same as Relational Algebra**

In [82]:

df1 = pd.DataFrame({'account_name': ['Lim', 'Jack', 'Sam', 'Lee'],
'type': ['Savings', 'Current', 'Loan', 'Savings']})
df2 = pd.DataFrame({'account_name': ['Lee', 'Lim', 'Sam', 'Jack'],
'amount': [10000, 70000, -20000, 50000]})

df3 = pd.merge (df1, df2)

print (df3)

  account_name     type  amount
0          Lim  Savings   70000
1         Jack  Current   50000
2          Sam     Loan  -20000
3          Lee  Savings   10000


In [85]:
x = np.array ([[12,5,2,4],[ 7,6,8,8],[ 1,6 ,7, 7]])
x_sub = x[:2, :2]
x_sub[1,1] = 8
print(x[1,1])

8


In [86]:
x=np.array([1,2,3,4,5])

In [87]:
np.linspace(1, 10, 5)



array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [88]:
df1 = pd.DataFrame({'account_name': ['Lim', 'Jack', 'Sam', 'Lee'],
'type': ['Savings', 'Current', 'Loan', 'Savings']})

df2 = pd.DataFrame({'type': ['Savings', 'Loan', 'Current'],
'interestRate': [2, 8, 3]})
df3 = pd.merge (df1, df2)

print (df3)

  account_name     type  interestRate
0          Lim  Savings             2
1          Lee  Savings             2
2         Jack  Current             3
3          Sam     Loan             8
